services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: app
    volumes:
      - app-data:/var/lib/postgres
    ports:
      - 8091:5432


volumes:
  app-data:
